name: face_exp_ta
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2022.07.19=h06a4308_0
  - certifi=2022.9.24=py39h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.3=h5eee18b_3
  - openssl=1.1.1q=h7f8727e_0
  - pip=22.2.2=py39h06a4308_0
  - python=3.9.13=haa1d7c7_1
  - readline=8.1.2=h7f8727e_1
  - setuptools=63.4.1=py39h06a4308_0
  - sqlite=3.39.3=h5082296_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.6=h5eee18b_0
  - zlib=1.2.12=h5eee18b_3
  - pip:
    - absl-py==1.2.0
    - altair==4.2.0
    - astunparse==1.6.3
    - attrs==22.1.0
    - bbox-visualizer==0.1.0
    - beautifulsoup4==4.11.1
    - bidict==0.22.0
    - blinker==1.5
    - cachetools==5.2.0
    - charset-normalizer==2.1.1
    - click==8.1.3
    - coloredlogs==15.0.1
    - commonmark==0.9.1
    - decorator==5.1.1
    - deepface==0.0.75
    - dlib==19.24.0
    - dnspython==2.2.1
    - entrypoints==0.4
    - eventlet==0.33.1
    - filelock==3.8.0
    - fire==0.4.0
    - flask==2.1.1
    - flask-socketio==5.3.1
    - flatbuffers==22.9.24
    - gast==0.4.0
    - gdown==4.5.1
    - gevent==22.8.0
    - gevent-socketio==0.3.6
    - gevent-websocket==0.10.1
    - gitdb==4.0.9
    - gitpython==3.1.28
    - google-auth==2.12.0
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - greenlet==1.1.3
    - grpcio==1.49.1
    - h5py==3.7.0
    - humanfriendly==10.0
    - idna==3.4
    - importlib-metadata==5.0.0
    - itsdangerous==2.1.2
    - jinja2==3.1.2
    - jsonpickle==2.2.0
    - jsonschema==4.16.0
    - keras==2.10.0
    - keras-preprocessing==1.1.2
    - libclang==14.0.6
    - markdown==3.4.1
    - markupsafe==2.1.1
    - mpmath==1.2.1
    - mtcnn==0.1.1
    - numpy==1.23.3
    - oauthlib==3.2.1
    - onnxruntime-gpu==1.12.1
    - opencv-python==4.6.0.66
    - opt-einsum==3.3.0
    - packaging==21.3
    - pandas==1.5.0
    - pillow==9.2.0
    - protobuf==3.19.6
    - pyarrow==9.0.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydeck==0.8.0b3
    - pygments==2.13.0
    - pympler==1.0.1
    - pyparsing==3.0.9
    - pyrsistent==0.18.1
    - pysocks==1.7.1
    - python-dateutil==2.8.2
    - python-engineio==4.3.4
    - python-socketio==5.7.1
    - pytz==2022.4
    - pytz-deprecation-shim==0.1.0.post0
    - requests==2.28.1
    - requests-oauthlib==1.3.1
    - retina-face==0.0.12
    - rich==12.6.0
    - rsa==4.9
    - semver==2.13.0
    - six==1.16.0
    - smmap==5.0.0
    - soupsieve==2.3.2.post1
    - streamlit==1.13.0
    - sympy==1.11.1
    - tensorboard==2.10.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow==2.10.0
    - tensorflow-addons==0.18.0
    - tensorflow-estimator==2.10.0
    - tensorflow-io-gcs-filesystem==0.27.0
    - termcolor==2.0.1
    - toml==0.10.2
    - toolz==0.12.0
    - tornado==6.2
    - tqdm==4.64.1
    - typeguard==2.13.3
    - typing-extensions==4.4.0
    - tzdata==2022.4
    - tzlocal==4.2
    - urllib3==1.26.12
    - validators==0.20.0
    - watchdog==2.1.9
    - werkzeug==2.2.2
    - wrapt==1.14.1
    - zipp==3.9.0
    - zope-event==4.5.0
    - zope-interface==5.4.0
# prefix: /home/millenia/miniconda3/envs/face_exp_ta
